# Generated by Django 2.1.7 on 2019-06-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='food',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='calories',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='kcal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(choices=[('TBSP', 'tbsp'), ('TSP', 'tsp'), ('CUP', 'cup'), ('OZ', 'oz'), ('HALF', 'half'), ('SERVING', 'serving'), ('PAT', 'pat'), ('SLICE', 'slice'), ('FL_OZ', 'fl_oz'), ('ITEM', 'item'), ('PKG', 'pkg')], default='ITEM', max_length=30),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
