# Generated by Django 2.1.7 on 2019-06-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20190603_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
