# Generated by Django 2.1.7 on 2019-06-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
