# Generated by Django 2.1.7 on 2019-06-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_auto_20190603_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
