# Generated by Django 2.1.7 on 2019-06-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_auto_20190603_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity_total',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='weight_total',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
