# Generated by Django 2.1.7 on 2019-06-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_auto_20190603_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
