# Generated by Django 2.1.7 on 2019-06-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_auto_20190603_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
