repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.4
    hooks:
    -   id: flake8
-   repo: https://github.com/szebenyib/pre-commit-pytest.git
    sha: '051fea31dbabf063ab38428c34a92c76d1abd5dc'
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
default_language_version:
  python: python3.7
dafault_stages: [commit, push]
fail_fast: true
