# Generated by Django 2.1.7 on 2019-06-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190530_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='quantities',
            new_name='amounts',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
