# Generated by Django 2.1.7 on 2019-06-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20190603_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='weight_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(),
        ),
    ]
