# Generated by Django 2.1.7 on 2019-06-03 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20190603_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity_total',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='weight_total',
        ),
    ]
