# Generated by Django 2.1.7 on 2019-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MealChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_choice', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], default='BREAKFAST', max_length=30)),
                ('day_plan', models.ForeignKey(on_delete='PROTECT', to='planner.DayPlan')),
                ('meal', models.ForeignKey(on_delete='PROTECT', to='meals.Meal')),
            ],
        ),
        migrations.AddField(
            model_name='dayplan',
            name='meals',
            field=models.ManyToManyField(related_name='dayplans', through='planner.MealChoice', to='meals.Meal'),
        ),
    ]
